SELECT TOP (1000) [Id]
      ,[Title]
      ,[Description]
      ,[EventDate]
      ,[EndTime]
      ,[Capacity]
      ,[VenueId]
      ,[CategoryId]
      ,[Status]
      ,[ImageUrl]
      ,[CreatedAt]
  FROM [EventParkingDB].[dbo].[Events]
